// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: unreliable_afs.proto
#ifndef GRPC_unreliable_5fafs_2eproto__INCLUDED
#define GRPC_unreliable_5fafs_2eproto__INCLUDED

#include "unreliable_afs.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace unreliable_afs {

class UnreliableAFS final {
 public:
  static constexpr char const* service_full_name() {
    return "unreliable_afs.UnreliableAFS";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // rpc GetAttr (GetAttrReq) returns (GetAttrReply) {}
    virtual ::grpc::Status Mkdir(::grpc::ClientContext* context, const ::unreliable_afs::MkdirRequest& request, ::unreliable_afs::MkdirReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::unreliable_afs::MkdirReply>> AsyncMkdir(::grpc::ClientContext* context, const ::unreliable_afs::MkdirRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::unreliable_afs::MkdirReply>>(AsyncMkdirRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::unreliable_afs::MkdirReply>> PrepareAsyncMkdir(::grpc::ClientContext* context, const ::unreliable_afs::MkdirRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::unreliable_afs::MkdirReply>>(PrepareAsyncMkdirRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // rpc GetAttr (GetAttrReq) returns (GetAttrReply) {}
      virtual void Mkdir(::grpc::ClientContext* context, const ::unreliable_afs::MkdirRequest* request, ::unreliable_afs::MkdirReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Mkdir(::grpc::ClientContext* context, const ::unreliable_afs::MkdirRequest* request, ::unreliable_afs::MkdirReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::unreliable_afs::MkdirReply>* AsyncMkdirRaw(::grpc::ClientContext* context, const ::unreliable_afs::MkdirRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::unreliable_afs::MkdirReply>* PrepareAsyncMkdirRaw(::grpc::ClientContext* context, const ::unreliable_afs::MkdirRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status Mkdir(::grpc::ClientContext* context, const ::unreliable_afs::MkdirRequest& request, ::unreliable_afs::MkdirReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::unreliable_afs::MkdirReply>> AsyncMkdir(::grpc::ClientContext* context, const ::unreliable_afs::MkdirRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::unreliable_afs::MkdirReply>>(AsyncMkdirRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::unreliable_afs::MkdirReply>> PrepareAsyncMkdir(::grpc::ClientContext* context, const ::unreliable_afs::MkdirRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::unreliable_afs::MkdirReply>>(PrepareAsyncMkdirRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void Mkdir(::grpc::ClientContext* context, const ::unreliable_afs::MkdirRequest* request, ::unreliable_afs::MkdirReply* response, std::function<void(::grpc::Status)>) override;
      void Mkdir(::grpc::ClientContext* context, const ::unreliable_afs::MkdirRequest* request, ::unreliable_afs::MkdirReply* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::unreliable_afs::MkdirReply>* AsyncMkdirRaw(::grpc::ClientContext* context, const ::unreliable_afs::MkdirRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::unreliable_afs::MkdirReply>* PrepareAsyncMkdirRaw(::grpc::ClientContext* context, const ::unreliable_afs::MkdirRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_Mkdir_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // rpc GetAttr (GetAttrReq) returns (GetAttrReply) {}
    virtual ::grpc::Status Mkdir(::grpc::ServerContext* context, const ::unreliable_afs::MkdirRequest* request, ::unreliable_afs::MkdirReply* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_Mkdir : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Mkdir() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Mkdir() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Mkdir(::grpc::ServerContext* /*context*/, const ::unreliable_afs::MkdirRequest* /*request*/, ::unreliable_afs::MkdirReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestMkdir(::grpc::ServerContext* context, ::unreliable_afs::MkdirRequest* request, ::grpc::ServerAsyncResponseWriter< ::unreliable_afs::MkdirReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Mkdir<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_Mkdir : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Mkdir() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::unreliable_afs::MkdirRequest, ::unreliable_afs::MkdirReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::unreliable_afs::MkdirRequest* request, ::unreliable_afs::MkdirReply* response) { return this->Mkdir(context, request, response); }));}
    void SetMessageAllocatorFor_Mkdir(
        ::grpc::MessageAllocator< ::unreliable_afs::MkdirRequest, ::unreliable_afs::MkdirReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::unreliable_afs::MkdirRequest, ::unreliable_afs::MkdirReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_Mkdir() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Mkdir(::grpc::ServerContext* /*context*/, const ::unreliable_afs::MkdirRequest* /*request*/, ::unreliable_afs::MkdirReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Mkdir(
      ::grpc::CallbackServerContext* /*context*/, const ::unreliable_afs::MkdirRequest* /*request*/, ::unreliable_afs::MkdirReply* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_Mkdir<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_Mkdir : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Mkdir() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Mkdir() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Mkdir(::grpc::ServerContext* /*context*/, const ::unreliable_afs::MkdirRequest* /*request*/, ::unreliable_afs::MkdirReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_Mkdir : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Mkdir() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_Mkdir() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Mkdir(::grpc::ServerContext* /*context*/, const ::unreliable_afs::MkdirRequest* /*request*/, ::unreliable_afs::MkdirReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestMkdir(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Mkdir : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Mkdir() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Mkdir(context, request, response); }));
    }
    ~WithRawCallbackMethod_Mkdir() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Mkdir(::grpc::ServerContext* /*context*/, const ::unreliable_afs::MkdirRequest* /*request*/, ::unreliable_afs::MkdirReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Mkdir(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Mkdir : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Mkdir() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::unreliable_afs::MkdirRequest, ::unreliable_afs::MkdirReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::unreliable_afs::MkdirRequest, ::unreliable_afs::MkdirReply>* streamer) {
                       return this->StreamedMkdir(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Mkdir() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Mkdir(::grpc::ServerContext* /*context*/, const ::unreliable_afs::MkdirRequest* /*request*/, ::unreliable_afs::MkdirReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedMkdir(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::unreliable_afs::MkdirRequest,::unreliable_afs::MkdirReply>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_Mkdir<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_Mkdir<Service > StreamedService;
};

}  // namespace unreliable_afs


#endif  // GRPC_unreliable_5fafs_2eproto__INCLUDED
